export const questions = {
  "Kite AI Assistant": [
    "Tell me about the latest updates in Kite AI",
    "What are the upcoming features in Kite AI?",
    "How can Kite AI improve my development workflow?",
    "What makes Kite AI unique in the market?",
    "How does Kite AI handle code completion?",
    "Can you explain Kite AI's machine learning capabilities?",
    "What programming languages does Kite AI support best?",
    "How does Kite AI integrate with different IDEs?",
    "What are the advanced features of Kite AI?",
    "How can I optimize my use of Kite AI?",
  ],
  "Crypto Price Assistant": [
    "What's the current market sentiment for Solana?",
    "Analyze Bitcoin's price movement in the last hour",
    "Compare ETH and BTC performance today",
    "Which altcoins are showing bullish patterns?",
    "Market analysis for top 10 cryptocurrencies",
    "Technical analysis for Polkadot",
    "Price movement patterns for Avalanche",
    "Polygon's market performance analysis",
    "Latest developments affecting BNB price",
    "Cardano's market outlook",
  ],
  "Transaction Analyzer": [],
};
